services:
  
  giteascm:
    container_name: giteascm
    image: ao/giteascm:alpine3
    build: /home/ahmetozkesek/workspaces/podman/gitea-build
    ports: 
      - "8081:8081"
    hostname: giteascm
    volumes: 
      - "scm_data_vol:/var/gitrepo"
    networks:
      - br192_167

  jenkinscid:
    container_name: jenkinscid
    depends_on: 
      - giteascm
    image: ao/jenkinscid:alpine3
    build: /home/ahmetozkesek/workspaces/podman/jenkins-build
    ports: 
      - "8080:8080"
    hostname: jenkinscid
    volumes: 
      - "cid_data_vol:/var/www/jenkins"
    networks:
      - br192_167

volumes:
  scm_data_vol:
    name: scm_data_vol
    driver: local

  cid_data_vol:
    name: cid_data_vol
    driver: local

networks:
  br192_167:
    name: br192_167
    ipam:
      driver: bridge
      config:
        - subnet: "192.167.100.0/24"
        - ip_range: "192.167.100.1/25"
        - gateway: "192.167.100.1"
