services:
  gitea-scm:
    container_name: "gitea-scm"
    image: "ao/gitea-sc:alpine3"
    ports: 
      - "8081:8081"
    hostname: "giteascm"
    dns: "192.167.55.1"
    volumes: 
      - "scm-vol:/var/gitrepo"
    network_mode: host
    networks:
      br192_167:
        ipv4_address: "192.167.55.130" 

  jenkins-cid:
    container_name: "jenkins-cid"
    depends_on: 
      - gitea-scm
    image: "ao/jenkins-ci:alpine3"
    ports: 
      - "8080:8080"
    hostname: "jenkinscid"
    dns: "192.167.55.1"
    extra_hosts:
      - "giteascm:192.167.55.130"
    volumes: 
      - "cid-vol:/var/www/jenkins"
    network_mode: host
    networks:
      br192_167:
        ipv4_address: "192.167.55.131" 

volumes:
  scm-vol:
    name: "scm-vol"
    driver: local
  cid-vol:
    name: "cid-vol"
    driver: local

networks:
  br192_167:
    name: "br192_167"
    ipam:
      driver: bridge
      config:
        - subnet: "192.167.55.0/24"
        - ip_range: "192.167.55.128/25"
        - gateway: "192.167.55.1"
