services:
  ao-alpine3:
    build: ./alpine3-build
    image: "ao/alpine:3"
    
  ao-devops:
    build: ./devops-build
    image: "ao/devops:3"
    extends:
      service: ao-alpine3
      
  giteascm:
    extends:
      service: ao-alpine3      
    build: ./gitea-build
    image: "ao/giteascm"
    container_name: giteascm
    hostname: giteascm
    ports:
      - "8081:8081"
    expose:
      - "8081"
    volumes: 
      - scm_data:/var/gitrepo
 
  jenkinscid:
    extends:
      service: ao-devops
    build: ./jenkins-build
    image: "ao/jenkinscid"
    container_name: jenkinscid
    depends_on: 
      - giteascm
    hostname: jenkinscid
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes: 
      - cid_data:/var/www/jenkins

