FROM ao/devop:alpine3

ENV BUILD_HOME="/var/buildbot"
ENV MASTER=$BUILD_HOME/master
ENV WORKER=$BUILD_HOME/worker

COPY master.py /tmp/master.cfg
COPY buildbot-start /usr/bin

RUN set -xe ; \
	#
	apk add util-linux libffi-dev py3-pip py3-wheel python3-dev \
		py3-cffi py3-twisted py3-yaml py3-cryptography \
		py3-sqlalchemy py3-sqlalchemy-migrate py3-dateutil \
		py3-jinja2; \
	#
	# buildbot server
	pip install buildbot; \
	pip install buildbot-www \
		buildbot-waterfall-view \
		buildbot-console-view \
		buildbot-grid-view; \
	#
	# buildbot-worker
	pip install buildbot-worker; 

VOLUME [ "$BUILD_HOME" ]

WORKDIR "$BUILD_HOME"

EXPOSE 8010

CMD sh /usr/bin/buildbot-start

