FROM ao/devop:f34

RUN set -xe ; \
	#
	# add git user
	useradd -mU -G adm -p "dev.Op-Sc" devopsc; \
	#
	# install git daemon 
	dnf install -y git git-daemon; \
	#
	# do basic tests
	git --version; 

VOLUME [ "/var/git" ]
EXPOSE 9418

CMD git daemon --verbose --base-path=/var/git/ --listen=devopsc
