FROM alpine:3

ENV GITREPO=/var/gitrepo

COPY gitea.tar.xz /tmp

RUN set -xe ; \
	#
	# install git  
	apk add coreutils bash xz git; \
	#
	# extract, rename and make executable the gitea
	tar xvf /tmp/gitea.tar.xz -C /usr/bin; \
	mv /usr/bin/gitea-1.15.2 /usr/bin/gitea; \
	chown root /usr/bin/gitea; \
	chgrp root /usr/bin/gitea; \
	chmod +x /usr/bin/gitea; \
	#
	# do basic tests
	gitea --version; \
	git --version; 

VOLUME [ "$GITREPO" ]
WORKDIR "$GITREPO"
EXPOSE 8081

CMD gitea \
	--config $GITREPO/custom/conf/app.ini \
	--custom-path $GITREPO/custom \
	--work-path $GITREPO \
	--port 8081 \
	web \
	--install-port 8081 
