FROM ao/devop:alpine3

ENV JENKINS_HOME="/var/www/jenkins" 

COPY jenkins.tar.xz /var/www/

RUN set -xe ; \
	#
	# create jenkins folder
	mkdir -p $JENKINS_HOME ; \
	#
	# install required packages for jenkins
	apk add freetype font-xfree86-type1; \
	#
	# extract war
	tar xvf /var/www/jenkins.tar.xz -C /var/www; \
	#
	# do basic tests
	java -jar /var/www/jenkins.war --usage ;

VOLUME [ "$JENKINS_HOME" ]

WORKDIR /var/www/

EXPOSE 8080

CMD java -jar jenkins.war
